config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: "lists#index"
  # resources :movies
  resources :lists do
    resources :bookmarks, only: %i[show new create edit]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie, uniqueness: { scope: :list }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
  # validates :list_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def index
    @bookmarks = Bookmark.all
  end

  def show
    @bookmark = Bookmark.find(params[:id])
  end

  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = List.find(params[:list_id])
    if @bookmark.save
      redirect_to list_path(@bookmark.list)
    else
      # redirect_to root_path
      flash[:notice] = 'Post successfully created'
    end
  end

  def edit
    @bookmark = Bookmark.find(params[:id])
  end

  def update
    @bookmark = Bookmark.find(params[:id])
    @bookmark.update(bookmark_params)
    redirect_to bookmark_path(@bookmark)
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to bookmarks_path, status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
    @list = List.new
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
    redirect_to list_path(@list)
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    @list.update(list_params)
    redirect_to list_path(@list)
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def list_params
    params.require(:list).permit(:name, :image_url)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    @movie.save
    redirect_to movie_path(@movie)
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    @movie.update(movie_params)
    redirect_to movie_path(@movie)
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path, status: :see_other
  end

  private

  def movie_params
    params.require(:movie).permit(:title, :overview, :poster_url, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/_form.html.erb
<div>
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.input :comment, placeholder: "Write a comment" %>
    <%= f.association :movie, collection: Movie.all, prompt: "Select a movie" %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/bookmarks/index.html.erb
<div id="bookmarks" class="d-flex justify-content-center">
  <div id="container_main" class="d-flex justify-content-center">
    <div id="my_bookmarks" class="me-auto">
      <div id="bookmark_cards_heading">
        <h2>My Bookmarks</h2>
      </div>
      <div id="bookmark_cards"  class="d-flex align-content-start flex-wrap">
        <% @bookmarks.each do |bookmark| %>
          <div class="card-category m-3" style="color: white; width: 18rem; height: 12rem; background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
            <%= link_to "#{bookmark.name}", bookmark_path(bookmark), class: "btn btn-success" %>
          </div>
        <% end %>
      </div>
    </div>
    <div id="button_create">
      <%= link_to "Create a movie bookmark", new_bookmark_path, class: "btn btn-success" %>
    </div>
  </div>
</div>

app/views/bookmarks/show.html.erb
<div class="d-flex justify-content-center m-3">
  <div class="card p-3">
    <div class="p-3">
      <h3><%= @bookmark.comment %></h3>
    </div>
    <div class="d-flex mt-3">
      <div class="p-3">
        <p><%=  %></p>
      </div>
    </div>
    <div class="p-3" id="links">
      <%= link_to "All bookmarks", bookmarks_path, class: "btn btn-primary" %>
      <%= link_to "Edit", edit_bookmark_path, class: "btn btn-success" %>
      <%= link_to "Delete", bookmark_path(@bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} , class: "btn btn-danger" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar bg-dark sticky-top">
      <div class="container">
        <a class="navbar-brand" href="#">
          <i class="fa-solid fa-film text-light"></i>
        </a>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div id="home">
  <!-- Modal CREATE LIST-->
  <div class="modal fade" id="createList" tabindex="-1" aria-labelledby="createListLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="createListLabel">New list</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <div id="form">
            <%= simple_form_for(@list) do |f| %>
              <%= f.error_notification %>
              <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
              <%= f.input :name %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              <%= f.button :submit, "Create List", class: "btn btn-success" %>
            <% end %>
        </div>
      </div>
    </div>
  </div>

  <!-- HEADER-->
  <div id="title" class="d-flex justify-content-center" style="background-image: url(https://images.unsplash.com/photo-1563381013529-1c922c80ac8d?q=80&w=2913&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D)">
    <div class="text-white">
      <h1>Save any kind of movies</h1>
      <h3>Classic</h3>
    </div>
  </div>

  <!-- CONTAINER LIST-->
  <div id="container" class="row">
    <div class="col-1"></div>
    <div id="my_lists" class="col">
      <div id="first-row" class="row">
        <div id="list_cards_heading" class="col">
          <h2>My Lists</h2>
        </div>
        <div id="trigger-modal" class="col d-flex align-items-center">
          <!-- Button trigger modal -->
          <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#createList">
            create List
          </button>
        </div>
      </div>

      <!-- CONTAINER LIST-->
      <div id="list_cards"  class="row g-2">
        <div class="row row-cols-1 row-cols-md-3 g-4">
          <% @lists.each do |list| %>
          <div class="col">
            <div class="card h-100">
              <img src="<%= list.image_url %>" class="card-img-top" alt="...">
              <div class="card-body">
                <h5 class="card-title"><%= link_to "#{list.name}", list_path(list), class: "btn", style: "color: black" %></h5>
              </div>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-1"></div>
  </div>
</div>

app/views/lists/show.html.erb
<!-- Modal ADD MOVIE -->
<div class="modal fade" id="addMovieModal" tabindex="-1" aria-labelledby="addMovieModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="addMovieModalLabel">add movie</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div>
          <%= simple_form_for [@list, @bookmark] do |f| %>
            <%= f.input :comment, placeholder: "Write a comment (at least )" %>
            <%= f.association :movie, collection: Movie.all, prompt: "Select a movie" %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <%= f.button :submit, "Add movie", class: "btn btn-primary" %>
          <% end %>
      </div>
    </div>
  </div>
</div>

<!-- Modal EDIT LIST-->
<div class="modal fade" id="editListModal" tabindex="-1" aria-labelledby="editListModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="editListModalLabel">Edit List</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div id="form">
          <%= simple_form_for(@list, method: :patch, url: list_path(@list)) do |f| %>
            <%= f.error_notification %>
            <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

            <div class="form-inputs">
              <%= f.input :name %>
              <%= f.input :image_url %>
            </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              <%= f.button :submit, "Update List", class: "btn btn-success" %>
          <% end %>
      </div>
    </div>
  </div>
</div>

<!-- DIV SHOW LIST-->
<div class="d-flex justify-content-center m-3">
  <div class="card p-3" style="background-image: url(<%= @list.image_url %>)">
    <div class="p-3">
      <h3><%= @list.name %></h3>
    </div>
    <div class="d-flex mt-3">
      <div class="p-3">
        <p><%=  %></p>
      </div>
    </div>
    <div class="p-3" id="links">
      <%= link_to "All Lists", lists_path, class: "btn btn-secondary" %>
      <!-- Button trigger modal ADD MOVIE -->
      <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addMovieModal">
        add movie
      </button>
      <!-- Button trigger modal EDIT LIST-->
      <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#editListModal">
        Edit
      </button>
      <%= link_to "Delete", list_path(@list), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} , class: "btn btn-danger" %>
    </div>
  </div>
</div>

<!-- CONTAINER MOVIES-->
<div id="movie_cards_container" class="d-flex justify-content-center">
  <div id="movie_cards" class="d-flex flex-row mb-3">
    <% @list.movies.each do |movie| %>
      <div class="card m-2" style="width: 18rem;">
        <img src="<%= movie.poster_url %>" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title"><%= movie.title %></h5>
          <p class="card-text"><%= movie.rating %></p>
          <a href="#" class="btn btn-primary">Go somewhere</a>
          <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
          <%= bookmark.comment %>
          <%# <% link_to "Delete" bookmark_path(bookmark) %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/movies/index.html.erb
<div id="home">
  <div id="navbar">

  </div>
  <div id="title" class="d-flex justify-content-center">
    <div>
      <h1>Headline Movie Index</h1>
      <h3>Subheading</h3>
    </div>
  </div>
  <div id="movies" class="d-flex justify-content-center">
    <div id="container_main" class="d-flex justify-content-center">
      <div id="my_movies" class="me-auto">
        <div id="movie_cards_heading">
          <h2>My Movies</h2>
        </div>
        <div id="movie_cards"  class="d-flex align-content-start flex-wrap">
          <% @movies.each do |movie| %>
            <div class="card-category m-3" style="color: white; width: 18rem; height: 12rem; background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
              <%= link_to "#{movie.title}", movie_path(movie), class: "btn btn-success" %>
            </div>
          <% end %>
        </div>
      </div>
      <div id="button_create">
        <%= link_to "Create a movie movie", new_movie_path, class: "btn btn-success" %>
      </div>
    </div>
  </div>
</div>

app/views/movies/show.html.erb
<div class="d-flex justify-content-center m-3">
  <div class="card p-3">
    <div class="p-3" >
      <h3><%= @movie.title %></h3>
    </div>
    <div class="d-flex mt-3">
      <div class="p-3">
        <p><%=  %></p>
      </div>
    </div>
    <div class="p-3" id="links">
      <%= link_to "All movies", movies_path, class: "btn btn-primary" %>
      <%= link_to "Edit", edit_movie_path, class: "btn btn-success" %>
      <%= link_to "Delete", movie_path(@movie), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} , class: "btn btn-danger" %>
    </div>
  </div>
</div>